### ISSUE TITLE
check size of mac electron build

### ISSUE THREAD

**Issue by pensoffsky** [pensoffsky/projectX#22]
compare windows vs. mac app size

**Comment by citoki** [comment]
**grunt-electron-app-builder** uses symlinks when platform [darwin](https://github.com/entropi/grunt-electron-app-builder#optionsplatforms) is used.
Unfortunately, **grunt-contrib-compress** [cannot support symlinks](https://github.com/gruntjs/grunt-contrib-compress/issues/167). This is seems to be an issue in [node-archiver](https://github.com/archiverjs/node-archiver/issues/158).

Therefor, as a workaround **grunt-shell** is used to zip files of darwin folder. The zip option **-y** is used to store symlinks as link.

**Comment by pensoffsky** [comment]
I run "grunt build" and the size of projectX-mac.zip is 142MB.
If i zip the build result manually in finder the size of the zip is 50MB. Mac build is still to big.
The size of the windows build is ok.

**Comment by pensoffsky** [comment]
After the changes the build on windows machines is not working anymore.

Running "shell:buildElectronDarwin" (shell) task
&& was unexpected at this time.
Warning: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "mkdir release &2>/dev/null && zip -yrq1 release/projectX-mac.zip build/projectX-executable/darwin/."
&& was unexpected at this time.
 Use --force to continue.

**Comment by pensoffsky** [comment]
fixed with os specific tasks in gruntbuild file
